unbind l
set -g prefix C-b
bind-key C-b last-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind c new-window -c "#{pane_current_path}"
bind n switch-client -t notes \; select-window -t notes

setw -g mode-keys vi

set -g default-terminal "tmux-256color"
set -s extended-keys always
set -as terminal-features 'tmux*:extkeys'

# Make OS X pasteboard available in tmux (see https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard)
set-option -g default-command "reattach-to-user-namespace -l zsh"

# Increase pane scrollback limit.
set-option -g history-limit 100000

# Start windows and panes at 1, not 0 (more logical finger-wise)
# https://unix.stackexchange.com/questions/35924/how-to-make-tmux-count-windows-starting-from-1-instead-of-0
set -g base-index 1
setw -g pane-base-index 1

# NeoVim health check:
#- ERROR `escape-time` (500) is higher than 300ms
#  - ADVICE:
#    - set escape-time in ~/.tmux.conf:
      set-option -sg escape-time 10
#    - https://github.com/neovim/neovim/blob/master/BUILD.md#building
#- WARNING `focus-events` is not enabled. |'autoread'| may not work.
#  - ADVICE:
#    - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
set-option -g focus-events on

# Switch to another session instead of exiting when destroying a session.
set-option -g detach-on-destroy off
