tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

cask "1password"
cask "alfred"
cask "anki"
cask "calibre"
cask "dropbox"
cask "evernote"
cask "firefox"
cask "iterm2"
cask "skype"
cask "tor-browser"
cask "transmission"
cask "vlc"
cask "whatsapp"

brew "ack"
brew "emacs"
brew "git-absorb"
brew "node" # For vim-instant-markdown
brew "rbenv"
brew "reattach-to-user-namespace"
brew "tmux"
brew "tree"
brew "vim"
brew "youtube-dl"
brew "ffmpeg" # Allows youtube-dl to merge best quality audio and video
