" ~/.vimrc_background is generated by the base16_<theme> command in zsh/base16-shell.sh
if filereadable(expand("~/.vimrc_background"))
    let base16colorspace=256
    source ~/.vimrc_background
endif
