#!/bin/bash
set -e
# e.g. TOOL_PATH=~/code/git-update-messages
TOOL_PATH=~/code/git-update-messages
COMMAND_PATH="bin/commands/git-update-messages"

if [[ -z  "${TOOL_PATH}" ]]
then
    echo "TOOL_PATH not set." 2>&1
    exit 1
fi

CURRENT_DIR=$(pwd)
cd "${TOOL_PATH}"
BUNDLER_PATH=$(rbenv which bundle)
cd "${CURRENT_DIR}"

export BUNDLE_GEMFILE="${TOOL_PATH}/Gemfile"
${BUNDLER_PATH} exec "${TOOL_PATH}/${COMMAND_PATH}" "$@"
